# data/generators/csv/generate_security_data.py
import csv
import os
import random
import sys
import numpy as np
from sentence_transformers import SentenceTransformer

# Ensure reproducibility across generator runs
random.seed(42)
np.random.seed(42)

def load_master_seeds(input_csv_path: str):
    """Loads prompt text, seed_id, and target label from the merged master CSV."""
    if not os.path.exists(input_csv_path):
        raise FileNotFoundError(f"[ERROR] Master input CSV not found at: {input_csv_path}")
    
    prompts = []
    labels = []
    seed_ids = []
    
    # Map alphanumeric seed_id strings (e.g., 'seed_gh_0001') to integer IDs for group splitting
    seed_id_map = {}
    current_integer_id = 0

    print(f"[Dataset Maker] Loading master seed dataset from:\n  -> {input_csv_path}")
    
    with open(input_csv_path, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            prompt_text = row["prompt_text"].strip()
            raw_seed = row["seed_id"].strip()
            target_label = int(row["target"])
            
            if raw_seed not in seed_id_map:
                seed_id_map[raw_seed] = current_integer_id
                current_integer_id += 1
                
            prompts.append(prompt_text)
            labels.append(target_label)
            seed_ids.append(seed_id_map[raw_seed])

    print(f"[Dataset Maker] Loaded {len(prompts)} total prompts across {len(seed_id_map)} unique seed families.")
    return prompts, labels, seed_ids

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.abspath(os.path.join(script_dir, "..", "..", ".."))
    
    # Path to the input balanced CSV generated by merge_datasets.py
    input_csv_path = os.path.join(repo_root, "data", "samples", "csv", "final_balanced_dataset.csv")
    
    # Path where the 384D embedding feature vector dataset will be saved
    target_data_dir = os.path.join(repo_root, "data", "samples", "csv")
    os.makedirs(target_data_dir, exist_ok=True)
    output_path = os.path.join(target_data_dir, "prompt_security_dataset.csv")

    # 1. Load data from CSV
    prompts, labels, seed_ids = load_master_seeds(input_csv_path)

    # 2. Encode prompts using SentenceTransformer
    print("[Dataset Maker] Loading SentenceTransformer model ('all-MiniLM-L6-v2')...")
    model = SentenceTransformer("all-MiniLM-L6-v2")

    print(f"[Dataset Maker] Extracting 384-dimensional embeddings for {len(prompts)} prompts...")
    embeddings = model.encode(prompts, show_progress_bar=True, batch_size=64)

    # 3. Format output matrix [f0, f1, ..., f383, seed_id, target]
    dataset_output = []
    for embedding, label, seed_id in zip(embeddings, labels, seed_ids):
        feature_vector = embedding.tolist()
        dataset_output.append(feature_vector + [seed_id, label])

    num_features = len(dataset_output[0]) - 2
    headers = [f"f{i}" for i in range(num_features)] + ["seed_id", "target"]

    # 4. Write dataset to disk
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(dataset_output)

    print(f"\n[Dataset Maker] SUCCESS! Published 384D feature vector dataset to:\n  -> {output_path}\n")

if __name__ == "__main__":
    main()